# Triggering first run
name: Log Petition Signatures

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  log-signatures:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run scraper
      run: python scrape.py

    - name: Commit log file
      run: |
        git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add data/
          git commit -m "Add data snapshot $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
